spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
# springboot fileupload
#  http.multipart:
#    max-file-size: 128KB
#    max-request-size: 128KB
## thymeleaf config
#  thymeleaf:
#    check-template-location: true

#logging:
#  level: info
#  path: /home/long/spring/logs


